[package]
name = "ns"
version = "0.1.0"
edition = "2021"

[lib]
name = "ns"
path = "src/lib.rs"

[[bin]]
name = "ns"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.32", features = ["derive"] }
colored = "2.1.0"
